// <auto-generated />
namespace BackboneSampe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_in_StatePOCO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_in_StatePOCO));
        
        string IMigrationMetadata.Id
        {
            get { return "201601050925269_Change_in_StatePOCO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
