// <auto-generated />
namespace BackboneSampe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_in_StatePOCO1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_in_StatePOCO1));
        
        string IMigrationMetadata.Id
        {
            get { return "201601050930327_Change_in_StatePOCO1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
